---
title: 'Reproducible Research: Course Project 2'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading libraries
```{r libraries}
#library(cacher)
library(dplyr)
library(lattice)
```

## Reading data

```{r read, cache=TRUE}
data <- read.csv("C:/Users/SamJacobJulian/Downloads/repdata%2Fdata%2FStormData.csv.bz2")
head(data[,1:5])
```

```{r max_fatalities}
data_evtype <- data %>% group_by(EVTYPE) %>% summarise(sum(FATALITIES))
length(unique(data$EVTYPE))
# Finding maximum fatalities
which.max(data_evtype$`sum(FATALITIES)`)
print(data_evtype[834,])
# Separating events with fatalities
fat_ind <- which(data_evtype$`sum(FATALITIES)`>0)
fat <- data_evtype[fat_ind,]
# Top 10 disastrous events in US history
fat_ord <- fat %>% arrange(desc((fat$`sum(FATALITIES)`)))
head(fat_ord,10)
```


```{r max_damage}
data_damage <- data %>% group_by(EVTYPE) %>% summarise(sum(PROPDMG))
# Finding maximum damages
which.max(data_damage$`sum(PROPDMG)`)
print(data_damage[834,])
# Separating events with fatalities
dam_ind <- which(data_damage$`sum(PROPDMG)`>0)
dam <- data_damage[dam_ind,]
# Top 10 disastrous events in US history
dam_ord <- dam %>% arrange(desc((dam$`sum(PROPDMG)`)))
head(dam_ord,10)
```
